/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cine.Indice;

import Archivo.Nodo;
import Cine.Cine;
import static Main.MenuPrincipal.getCine;

/**
 *
 * @author David Sandoval Salvador
 */
public class ListarIndice extends javax.swing.JInternalFrame {

    Cine cine = getCine();

    /**
     * Creates new form ListarIndicePrimario
     */
    public ListarIndice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarIndiceP = new javax.swing.JButton();
        btnListarIndiceS = new javax.swing.JButton();

        setClosable(true);
        setTitle("Listado Indice");
        setToolTipText("");

        btnListarIndiceP.setText("Listar Indice P");
        btnListarIndiceP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarIndicePActionPerformed(evt);
            }
        });

        btnListarIndiceS.setText("Listar Indice S");
        btnListarIndiceS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarIndiceSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarIndiceS)
                    .addComponent(btnListarIndiceP))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnListarIndiceP)
                .addGap(18, 18, 18)
                .addComponent(btnListarIndiceS)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarIndicePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarIndicePActionPerformed
        System.out.println("Listado del Indice Primario en Memoria");
        int i = 0;
        for (Nodo n : cine.getIndicePrimario()) {
            System.out.println("pos " + i + ": " + n.toString());
            i++;
        }
    }//GEN-LAST:event_btnListarIndicePActionPerformed

    private void btnListarIndiceSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarIndiceSActionPerformed
        System.out.println("Listado del Indice Secundario en Memoria");
        int i = 0;
        for (Nodo n : cine.getIndiceSecundario()) {
            System.out.println("pos " + i + ": " + n.toString());
            i++;
        }
    }//GEN-LAST:event_btnListarIndiceSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarIndiceP;
    private javax.swing.JButton btnListarIndiceS;
    // End of variables declaration//GEN-END:variables
}
