/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cine.Indice;

import Cine.Cine;
import static Main.MenuPrincipal.getCine;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author David Sandoval Salvador
 */
public class Reconstruccion extends javax.swing.JInternalFrame {

    Cine cine = getCine();

    /**
     * Creates new form Reconstruccion
     */
    public Reconstruccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReconstruccion = new javax.swing.JButton();

        btnReconstruccion.setText("Reconstruccion");
        btnReconstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconstruccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnReconstruccion)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnReconstruccion)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReconstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconstruccionActionPerformed
        try {
            cine.ReconstruccionIndicePrimario();
        } catch (IOException ex) {
            Logger.getLogger(Reconstruccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReconstruccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReconstruccion;
    // End of variables declaration//GEN-END:variables
}
