/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Cine.Indice;

import Cine.Cine;
import static Main.MenuPrincipal.getCine;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author David Sandoval Salvador
 */
public class Reconstruccion extends javax.swing.JInternalFrame {

    Cine cine = getCine();

    /**
     * Creates new form Reconstruccion
     */
    public Reconstruccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReconstruccionIP = new javax.swing.JButton();
        btnReconstruccionIS = new javax.swing.JButton();

        setClosable(true);
        setTitle("Reconstruccion del Indice");

        btnReconstruccionIP.setText("Reconstruccion IP");
        btnReconstruccionIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconstruccionIPActionPerformed(evt);
            }
        });

        btnReconstruccionIS.setText("Reconstruccion IS");
        btnReconstruccionIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconstruccionISActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReconstruccionIS)
                    .addComponent(btnReconstruccionIP))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnReconstruccionIP)
                .addGap(18, 18, 18)
                .addComponent(btnReconstruccionIS)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReconstruccionIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconstruccionIPActionPerformed
        try {
            cine.ReconstruccionIndicePrimario();
        } catch (IOException ex) {
            Logger.getLogger(Reconstruccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReconstruccionIPActionPerformed

    private void btnReconstruccionISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconstruccionISActionPerformed
        try {
            cine.ReconstruccionIndiceSecundario();
        } catch (IOException ex) {
            Logger.getLogger(Reconstruccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReconstruccionISActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReconstruccionIP;
    private javax.swing.JButton btnReconstruccionIS;
    // End of variables declaration//GEN-END:variables
}
