/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Archivo.Archivo;
import Cine.Actualizacion.Consultar;
import Cine.Actualizacion.Eliminar;
import Cine.Actualizacion.Listado;
import Cine.Actualizacion.Modificar;
import Cine.Actualizacion.Registrar;
import Cine.Cine;
import Cine.Indice.Reconstruccion;
import Cine.Mantenimiento.ClasificacionIndirecciones;
import Cine.Mantenimiento.ClasificacionNodos;
import Cine.Mantenimiento.ClasificacionRAM;
import Cine.Mantenimiento.CompactarInSitu;
import Cine.Mantenimiento.CompactarPorCopia;
import Cine.Mantenimiento.Fragmentacion;
import Pelicula.Pelicula;
import Proyeccion.Proyeccion;
import Sala.Sala;
import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sando
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static Archivo[] archivos;
    private static Cine cine;
    private static Sala sala;
    private static Pelicula pelicula;
    private static Proyeccion proyeccion;

    public static Archivo[] getArchivos() {
        return archivos;
    }

    public static void setArchivos(Archivo[] archivos) {
        MenuPrincipal.archivos = archivos;
    }

    public static Cine getCine() {
        return cine;
    }

    public static void setCine(Cine cine) {
        MenuPrincipal.cine = cine;
    }

    public static Sala getSala() {
        return sala;
    }

    public static void setSala(Sala sala) {
        MenuPrincipal.sala = sala;
    }

    public static Pelicula getPelicula() {
        return pelicula;
    }

    public static void setPelicula(Pelicula pelicula) {
        MenuPrincipal.pelicula = pelicula;
    }

    public static Proyeccion getProyeccion() {
        return proyeccion;
    }

    public static void setProyeccion(Proyeccion proyeccion) {
        MenuPrincipal.proyeccion = proyeccion;
    }

    public MenuPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ActualizarCine = new javax.swing.JMenu();
        RegistrarCine = new javax.swing.JMenuItem();
        EliminarCine = new javax.swing.JMenuItem();
        ListarCine = new javax.swing.JMenuItem();
        ConsultarCine = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MantenimientoCine = new javax.swing.JMenu();
        GrafmentacionCine = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        CompactacionCopiaCine = new javax.swing.JMenuItem();
        CompactacionInSitu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        ClasificacionRAM = new javax.swing.JMenuItem();
        ClasificacionNodos = new javax.swing.JMenuItem();
        ClasificacionIndirecciones = new javax.swing.JMenuItem();
        IndiceCine = new javax.swing.JMenu();
        ReconstruccionCine = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de salas de cine");

        Escritorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseMoved(evt);
            }
        });

        jMenu1.setText("Cine");

        ActualizarCine.setText("Actualizar");

        RegistrarCine.setText("Registrar");
        RegistrarCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarCineActionPerformed(evt);
            }
        });
        ActualizarCine.add(RegistrarCine);

        EliminarCine.setText("Eliminar");
        EliminarCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCineActionPerformed(evt);
            }
        });
        ActualizarCine.add(EliminarCine);

        ListarCine.setText("Listar");
        ListarCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCineActionPerformed(evt);
            }
        });
        ActualizarCine.add(ListarCine);

        ConsultarCine.setText("Consultar");
        ConsultarCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarCineActionPerformed(evt);
            }
        });
        ActualizarCine.add(ConsultarCine);

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ActualizarCine.add(jMenuItem1);

        jMenu1.add(ActualizarCine);

        MantenimientoCine.setText("Mantenimiento");

        GrafmentacionCine.setText("Fragmentacion");
        GrafmentacionCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrafmentacionCineActionPerformed(evt);
            }
        });
        MantenimientoCine.add(GrafmentacionCine);

        jMenu5.setText("Compactacion");

        CompactacionCopiaCine.setText("Copia");
        CompactacionCopiaCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompactacionCopiaCineActionPerformed(evt);
            }
        });
        jMenu5.add(CompactacionCopiaCine);

        CompactacionInSitu.setText("IN-SISTU");
        CompactacionInSitu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompactacionInSituActionPerformed(evt);
            }
        });
        jMenu5.add(CompactacionInSitu);

        MantenimientoCine.add(jMenu5);

        jMenu6.setText("Clasificacion");

        ClasificacionRAM.setText("RAM");
        ClasificacionRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasificacionRAMActionPerformed(evt);
            }
        });
        jMenu6.add(ClasificacionRAM);

        ClasificacionNodos.setText("Nodos");
        ClasificacionNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasificacionNodosActionPerformed(evt);
            }
        });
        jMenu6.add(ClasificacionNodos);

        ClasificacionIndirecciones.setText("Indirecciones");
        ClasificacionIndirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasificacionIndireccionesActionPerformed(evt);
            }
        });
        jMenu6.add(ClasificacionIndirecciones);

        MantenimientoCine.add(jMenu6);

        jMenu1.add(MantenimientoCine);

        IndiceCine.setText("Indices");

        ReconstruccionCine.setText("Reconstruccion");
        ReconstruccionCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReconstruccionCineActionPerformed(evt);
            }
        });
        IndiceCine.add(ReconstruccionCine);

        jMenu1.add(IndiceCine);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sala");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pelicula");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Proyeccion");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1MouseMoved

    private void EliminarCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCineActionPerformed
        Eliminar ic = new Eliminar();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_EliminarCineActionPerformed

    private void RegistrarCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCineActionPerformed
        Registrar ic = new Registrar();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_RegistrarCineActionPerformed

    private void ListarCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCineActionPerformed
        Listado ic = new Listado();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_ListarCineActionPerformed

    private void ConsultarCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarCineActionPerformed
        Consultar ic = new Consultar();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_ConsultarCineActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Modificar ic = new Modificar();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void GrafmentacionCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrafmentacionCineActionPerformed
        Fragmentacion ic = new Fragmentacion();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_GrafmentacionCineActionPerformed

    private void CompactacionCopiaCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompactacionCopiaCineActionPerformed
        CompactarPorCopia ic = new CompactarPorCopia();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_CompactacionCopiaCineActionPerformed

    private void CompactacionInSituActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompactacionInSituActionPerformed
        CompactarInSitu ic = new CompactarInSitu();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_CompactacionInSituActionPerformed

    private void ClasificacionRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasificacionRAMActionPerformed
        ClasificacionRAM ic = new ClasificacionRAM();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_ClasificacionRAMActionPerformed

    private void ClasificacionNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasificacionNodosActionPerformed
        ClasificacionNodos ic = new ClasificacionNodos();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_ClasificacionNodosActionPerformed

    private void ClasificacionIndireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasificacionIndireccionesActionPerformed
        ClasificacionIndirecciones ic = new ClasificacionIndirecciones();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_ClasificacionIndireccionesActionPerformed

    private void ReconstruccionCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReconstruccionCineActionPerformed
        Reconstruccion ic = new Reconstruccion();
        Escritorio.add(ic);
        ic.show();
    }//GEN-LAST:event_ReconstruccionCineActionPerformed

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatArcIJTheme());
        java.awt.EventQueue.invokeLater(() -> {
            MenuPrincipal v = new MenuPrincipal();
            v.setVisible(true);
            v.setLocationRelativeTo(null);

            archivos = new Archivo[4];
            cine = new Cine("Cines", "dat");
            sala = new Sala("Salas", "dat");
            pelicula = new Pelicula("Peliculas", "dat");
            proyeccion = new Proyeccion("Proyecciones", "dat");

            archivos[0] = cine;
            archivos[1] = sala;
            archivos[2] = pelicula;
            archivos[3] = proyeccion;

            int i = 0;
            while (i < 1) {
                try {
                    archivos[i].CrearArchivo();
                    archivos[i].CrearArchivoIdices();
                    archivos[i].CargarIndicePrimario();
                    i++;
                } catch (IOException ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ActualizarCine;
    private javax.swing.JMenuItem ClasificacionIndirecciones;
    private javax.swing.JMenuItem ClasificacionNodos;
    private javax.swing.JMenuItem ClasificacionRAM;
    private javax.swing.JMenuItem CompactacionCopiaCine;
    private javax.swing.JMenuItem CompactacionInSitu;
    private javax.swing.JMenuItem ConsultarCine;
    private javax.swing.JMenuItem EliminarCine;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem GrafmentacionCine;
    private javax.swing.JMenu IndiceCine;
    private javax.swing.JMenuItem ListarCine;
    private javax.swing.JMenu MantenimientoCine;
    private javax.swing.JMenuItem ReconstruccionCine;
    private javax.swing.JMenuItem RegistrarCine;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
